max_depth:
   min: 2
   max: 30 
   interval: 1
   distribution: quniform
   dtype: int

n_estimators:
   min: 2
   max: 500 
   interval: 1
   distribution: quniform
   dtype: int


pos_weight:
   min: .01
   max: .9
   interval: None
   distribution: uniform
   dtype: float